#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "llms-config.json"
INDEX_PATH = ROOT / "llms.txt"
FULL_PATH = ROOT / "llms-full.txt"


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text())


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def render_index(config: dict) -> str:
    lines = [
        f"# {config['project']}",
        "",
        config["tagline"],
        "",
        f"Canonical full context: {config['canonical']}",
        "",
        "## Included files",
        "",
    ]
    for item in config["files"]:
        lines.append(f"- `{item['path']}`: {item['title']}. {item['summary']}")
    lines.append("")
    lines.append("Generated by `scripts/build-llms.py` from `llms-config.json`.")
    return "\n".join(lines) + "\n"


def render_full(config: dict) -> str:
    lines = [
        f"# {config['project']} full context",
        "",
        config["tagline"],
        "",
        "Generated by `scripts/build-llms.py` from `llms-config.json`.",
        "",
    ]
    for item in config["files"]:
        path = ROOT / item["path"]
        body = path.read_text()
        lines.extend([
            f"## {item['title']}",
            "",
            f"Source: `{rel(path)}`",
            "",
            body.rstrip(),
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    config = load_config()
    INDEX_PATH.write_text(render_index(config))
    FULL_PATH.write_text(render_full(config))
    print(f"Wrote {rel(INDEX_PATH)} and {rel(FULL_PATH)}")


if __name__ == "__main__":
    main()
